insert into region (id , region_name)
VALUES           (1,  'NORTH_INDIAN'),
                 (2,  'SOUTH_INDIAN'),
                 (3,  'EAST_INDIAN'),
                 (4,  'WEST_INDIAN'),
                 (5,  'ANDRA_STYLE'),
                 (6,  'KARNATAKA_STYLE'),
                 (7,  'UTTARA_KARNATAKA_STYLE'),
                 (8,  'GOAN_STYLE'),
                 (9,  'MUMBUY_STYLE'),
                 (10, 'MYSURIAN_STYLE'),
                 (11, 'BENGALURIAN_STYLE');

insert into hotel (id, hotel_address , hotel_name, hotel_ratings, region_id)
values  (1,'Indranagar 1th Phase Bangalore' , 'Sagar hotel' , 4 , 1),
        (2,'Jaya Nagar 12th Phase Bangalore' , 'A2B hotel' , 4 , 2),
        (3,'C V Raman Nagar 14th Phase Bangalore' , 'Krishna hotel' , 4 , 1),
        (4,'Vijayanagar 7th Layout Bangalore' , 'Miltry hotel' , 4 , 3),
        (5,'Basawashwar Nagar 29th main Bangalore' , 'Al-Bake hotel' , 4 , 4),
        (6,'Chandra Nagar 7th Phase Bangalore' , 'Janigadar hotel' , 4 , 3),
        (7,'Laxmi Layout 7th Phase Bangalore' , 'Abhi hotel' , 4 , 5),
        (8,'Basavannagoddi 17th main,2nd cross Bangalore' , 'Kappila hotel' , 4 , 2),
        (9,'Kanigiri 18th main,Bangalore' , 'Lila hotel' , 4 , 11),
        (10,'RR Nagar 1st sector Bangalore' ,'Tiffin mane hotel' , 4 , 10),
        (11,'MM Nagar ,Bangalore' ,'Manivoota hotel' , 4 , 9),
        (12,'Domallur bridge,14th main, 2nd A Cross,Bangalore' , 'Harsh hotel' , 4 , 8),
        (13,'HAL 2nd Stage Bangalore' , 'Kanpur hotel' , 4 , 7),
        (14,'HAL 2nd Stage 100ft road, Bangalore' , 'Panjabi hotel' , 4 , 6),
        (15,'Ajji Layout,2nd main, 14th cross road,Bangalore' , 'Wali hotel' , 4 , 5),
        (16,'Kamala layout Bangalore' , 'Bali hotel' , 4 , 4),
        (17,'Hosa Halli Bangalore' , 'Maggi hotel' , 4 , 3),
        (18,'Puttaninahalli Bangalore' , 'MTR hotel' , 4 , 3),
        (19,'Nagarbhavi 18th main 2nd cross,Bangalore' , 'Reo hotel' , 4 , 2),
        (20,'Jalahalli 17th cross, 2nd main, Bangalore' , 'Shubodhaya hotel' , 4 , 1),
        (22,'K R Market Bangalore' , 'Deepa hotel' , 4 , 7),
        (23,'Gandhi nagar Bangalore' , 'Ganesh hotel' , 4 , 8);
