insert into region (id , region_name)
VALUES           (1,  'NORTH_INDIAN'),
                 (2,  'SOUTH_INDIAN'),
                 (3,  'EAST_INDIAN'),
                 (4,  'WEST_INDIAN'),
                 (5,  'ANDRA_STYLE'),
                 (6,  'KARNATAKA_STYLE'),
                 (7,  'UTTARA_KARNATAKA_STYLE'),
                 (8,  'GOAN_STYLE'),
                 (9,  'MUMBUY_STYLE'),
                 (10, 'MYSURIAN_STYLE'),
                 (11, 'BENGALURIAN_STYLE');

insert into hotel (id, hotel_address , hotel_name, hotel_ratings, region_id)
values  (1,'JP Nagar 7th Phase Bangalore' , 'Sagar hotel' , 4 , 1),
        (2,'JP Nagar 7th Phase Bangalore' , 'A2B hotel' , 4 , 2),
        (3,'JP Nagar 7th Phase Bangalore' , 'Krishna hotel' , 4 , 1),
        (4,'JP Nagar 7th Phase Bangalore' , 'Miltry hotel' , 4 , 3),
        (5,'JP Nagar 7th Phase Bangalore' , 'Al-Bake hotel' , 4 , 4),
        (6,'JP Nagar 7th Phase Bangalore' , 'Janigadar hotel' , 4 , 3),
        (7,'JP Nagar 7th Phase Bangalore' , 'Abhi hotel' , 4 , 5),
        (8,'JP Nagar 7th Phase Bangalore' , 'Kappila hotel' , 4 , 2),
        (9,'JP Nagar 7th Phase Bangalore' , 'Lila hotel' , 4 , 11),
        (10,'JP Nagar 7th Phase Bangalore' ,'Tiffin mane hotel' , 4 , 10),
        (11,'JP Nagar 7th Phase Bangalore' ,'Manivoota hotel' , 4 , 9),
        (12,'JP Nagar 7th Phase Bangalore' , 'Harsh hotel' , 4 , 8),
        (13,'JP Nagar 7th Phase Bangalore' , 'Kanpur hotel' , 4 , 7),
        (14,'JP Nagar 7th Phase Bangalore' , 'Panjabi hotel' , 4 , 6),
        (15,'JP Nagar 7th Phase Bangalore' , 'Wali hotel' , 4 , 5),
        (16,'JP Nagar 7th Phase Bangalore' , 'Bali hotel' , 4 , 4),
        (17,'JP Nagar 7th Phase Bangalore' , 'Maggi hotel' , 4 , 3),
        (18,'JP Nagar 7th Phase Bangalore' , 'MTR hotel' , 4 , 3),
        (19,'JP Nagar 7th Phase Bangalore' , 'Reo hotel' , 4 , 2),
        (20,'JP Nagar 7th Phase Bangalore' , 'Shubodhaya hotel' , 4 , 1),
        (22,'JP Nagar 7th Phase Bangalore' , 'Deepa hotel' , 4 , 7),
        (23,'JP Nagar 7th Phase Bangalore' , 'Ganesh hotel' , 4 , 8);
